---

name: Automatic update of developer tools

on:
  schedule:
    # Run every week on Sunday at 00:00 AM UTC
    - cron: '0 0 * * 0'

jobs:
  build:
    name: Update tools
    runs-on: [ubuntu-latest]

    steps:
      - name: Run phive install (master)
        uses: actions/github-script@v6
        with:
          # Token has to be generated on a user account that controls the remote repository.
          # The _only_ scope to select is "Access public repositories", nothing more.
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'simplesamlphp',
              repo: 'simplesamlphp-test-framework',
              workflow_id: 'build-tools.yml',
              ref: 'master'
            })

    steps:
      - name: Run phive install (release-latest)
        uses: actions/github-script@v6
        with:
          # Token has to be generated on a user account that controls the remote repository.
          # The _only_ scope to select is "Access public repositories", nothing more.
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'simplesamlphp',
              repo: 'simplesamlphp-test-framework',
              workflow_id: 'build-tools.yml',
              ref: 'release-1.4'
            })
