---

on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      repository:
        description: 'The repository that needs linting'
        type: string
        default: ${{ github.repository }}
        required: false
      ref:
        description: 'The branch, tag or SHA that needs linting'
        type: string
        required: false
        default: ${{ github.ref }}
      pattern:
        description: 'The file-pattern to match files that are being linted'
        type: string
        required: false
        default: '**/*.{css,scss,sass}'
      config_file:
        description: 'The location of the linter-configuration'
        type: string
        required: false
        default: 'tools/linters/.stylelintrc.json'

jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.ref }}

      - name: Install StyleLint
        run: npm install stylelint stylelint-config-standard

      - name: Lint stylesheets
        run: ./node_modules/.bin/stylelint -f verbose -c=${{ inputs.config_file }} ${{ inputs.pattern }}
