---

on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      repository:
        description: 'The repository that needs linting'
        type: string
        default: ${{ github.repository }}
        required: false
      ref:
        description: 'The branch, tag or SHA that needs linting'
        type: string
        required: false
        default: ${{ github.ref }}
      config_file:
        description: 'The location of the linter-configuration'
        type: string
        required: false
        default: 'tools/linters/xmllinter.json'
  workflow_dispatch:

jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.ref }}

      - name: Read JSON file  # this puts the whole JSON file in the read-json step output
        id: read-json
        run: |  # to read multi-line JSON file and not bother with escaping
          if [ -f "${{ inputs.config_file }}" ]; then
            echo "config<<EOF" >> $GITHUB_OUTPUT
            cat ${{ inputs.config_file }} >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          else
            echo "config={}" >> $GITHUB_OUTPUT
          fi

      - name: Find all XML-files in this repository
        id: find-xml
        run: |
          FILES=`find . -type f -iname "*.xml"`
          #if [[ "${FILES}" != "" ]]; then
          #  JSON=`printf '%s\n' "${FILES[@]}" | jq -R . | jq -s .`
          #  echo "files=${JSON}" >> $GITHUB_OUTPUT
          #else
          #  echo "files={}" >> $GITHUB_OUTPUT
          #fi
          echo "files=${FILES}" >> $GITHUB_OUTPUT

      - name: Lint XML
        run: |
          #echo ${{ contains(fromJSON(steps.read-json.outputs.config).ignore, 'bullshit') }}
          #echo ${{ contains(fromJSON(steps.read-json.outputs.config).ignore, '/path/to/file') }}
          for fn in ${{ steps.find-xml.outputs.files }}; do
            echo "the next file is $fn"
            cat $fn
          done
